###
GET http://localhost:8000/api/v1/
Content-Type: application/json

{
    "task": "doing",

    "hour": 10,

    "type": "entry"
}
###
POST  http://localhost:8000/api/v1/
Content-Type: application/json

{
    "task": "reading",

    "hour": 3,

    "type": "entry"
}

### patch method
PATCH http://localhost:8000/api/v1
Content-Type: application/json

{
    "task": "reading",

    "hour": 2,

    "type": "entry"
}

### delete method

DELETE  http://localhost:8000/api/v1/: 
Content-Type: application/json


